from odoo import fields, models, api
from datetime import timedelta

class estatePropertyOffer(models.Model):
    _name = "estate.property.offer"
    _description = "offers available to property"

    price = fields.Float("Price")
    status = fields.Selection(string = "Status", copy = False, selection = [("accepted", "Accepted"), ("refused", "Refused")])
    partner_id = fields.Many2one("res.partner", required=True)
    property_id = fields.Many2one("estate.property", required=True)

    validity = fields.Integer("Validity (days)",  default = 7)
    date_deadline = fields.Date("Deadline Date", compute = "_compute_date_deadline", inverse = "_inverse_date_deadline")

    @api.depends("validity", "property_id.create_date") #create_date is a automatic field generated by ORM
    def _compute_date_deadline(self):
        for record in self:
            createDate = record.property_id.create_date.date() if record.property_id and record.property_id.create_date else fields.Date.today()
            record.date_deadline = createDate + timedelta(days=record.validity)

    def _inverse_date_deadline(self):
        for record in self:
            record.validity = (record.date_deadline - record.property_id.create_date.date()).days if record.date_deadline else 0
