repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [ --fix ] # To automatycznie naprawi co się da!
      - id: ruff-format # To zastępuje Blacka i dba o długość linii