                                    List of relations
 Schema |                            Name                             |   Type   | Owner 
--------+-------------------------------------------------------------+----------+-------
 public | account_account                                             | table    | odoo
 public | account_account_account_auto_reconcile_wizard_rel           | table    | odoo
 public | account_account_account_merge_wizard_rel                    | table    | odoo
 public | account_account_account_tag                                 | table    | odoo
 public | account_account_exclude_res_currency_provision              | table    | odoo
 public | account_account_fiscal_rate                                 | table    | odoo
 public | account_account_fiscal_rate_id_seq                          | sequence | odoo
 public | account_account_id_seq                                      | sequence | odoo
 public | account_account_res_company_rel                             | table    | odoo
 public | account_account_tag                                         | table    | odoo
 public | account_account_tag_account_move_line_rel                   | table    | odoo
 public | account_account_tag_account_tax_repartition_line_rel        | table    | odoo
 public | account_account_tag_id_seq                                  | sequence | odoo
 public | account_account_tag_product_template_rel                    | table    | odoo
 public | account_account_tax_default_rel                             | table    | odoo
 public | account_accrued_orders_wizard                               | table    | odoo
 public | account_accrued_orders_wizard_id_seq                        | sequence | odoo
 public | account_analytic_account                                    | table    | odoo
 public | account_analytic_account_id_seq                             | sequence | odoo
 public | account_analytic_applicability                              | table    | odoo
 public | account_analytic_applicability_id_seq                       | sequence | odoo
 public | account_analytic_distribution_model                         | table    | odoo
 public | account_analytic_distribution_model_id_seq                  | sequence | odoo
 public | account_analytic_line                                       | table    | odoo
 public | account_analytic_line_id_seq                                | sequence | odoo
 public | account_analytic_plan                                       | table    | odoo
 public | account_analytic_plan_id_seq                                | sequence | odoo
 public | account_audit_account_status                                | table    | odoo
 public | account_audit_account_status_id_seq                         | sequence | odoo
 public | account_auto_reconcile_wizard                               | table    | odoo
 public | account_auto_reconcile_wizard_account_move_line_rel         | table    | odoo
 public | account_auto_reconcile_wizard_id_seq                        | sequence | odoo
 public | account_auto_reconcile_wizard_res_partner_rel               | table    | odoo
 public | account_automatic_entry_wizard                              | table    | odoo
 public | account_automatic_entry_wizard_account_move_line_rel        | table    | odoo
 public | account_automatic_entry_wizard_id_seq                       | sequence | odoo
 public | account_autopost_bills_wizard                               | table    | odoo
 public | account_autopost_bills_wizard_id_seq                        | sequence | odoo
 public | account_bank_selection                                      | table    | odoo
 public | account_bank_selection_id_seq                               | sequence | odoo
 public | account_bank_statement                                      | table    | odoo
 public | account_bank_statement_id_seq                               | sequence | odoo
 public | account_bank_statement_ir_attachment_rel                    | table    | odoo
 public | account_bank_statement_line                                 | table    | odoo
 public | account_bank_statement_line_id_seq                          | sequence | odoo
 public | account_bank_statement_line_transient                       | table    | odoo
 public | account_bank_statement_line_transient_id_seq                | sequence | odoo
 public | account_cash_rounding                                       | table    | odoo
 public | account_cash_rounding_id_seq                                | sequence | odoo
 public | account_change_lock_date                                    | table    | odoo
 public | account_change_lock_date_id_seq                             | sequence | odoo
 public | account_duplicate_transaction_wizard                        | table    | odoo
 public | account_duplicate_transaction_wizard_id_seq                 | sequence | odoo
 public | account_financial_year_op                                   | table    | odoo
 public | account_financial_year_op_id_seq                            | sequence | odoo
 public | account_fiscal_category                                     | table    | odoo
 public | account_fiscal_category_id_seq                              | sequence | odoo
 public | account_fiscal_position                                     | table    | odoo
 public | account_fiscal_position_account                             | table    | odoo
 public | account_fiscal_position_account_id_seq                      | sequence | odoo
 public | account_fiscal_position_account_tax_rel                     | table    | odoo
 public | account_fiscal_position_id_seq                              | sequence | odoo
 public | account_fiscal_position_res_country_state_rel               | table    | odoo
 public | account_fiscal_year                                         | table    | odoo
 public | account_fiscal_year_id_seq                                  | sequence | odoo
 public | account_followup_followup_line                              | table    | odoo
 public | account_followup_followup_line_id_seq                       | sequence | odoo
 public | account_followup_followup_line_res_users_rel                | table    | odoo
 public | account_followup_manual_reminder                            | table    | odoo
 public | account_followup_manual_reminder_id_seq                     | sequence | odoo
 public | account_followup_manual_reminder_ir_attachment_rel          | table    | odoo
 public | account_followup_missing_information_wizard                 | table    | odoo
 public | account_followup_missing_information_wizard_id_seq          | sequence | odoo
 public | account_full_reconcile                                      | table    | odoo
 public | account_full_reconcile_id_seq                               | sequence | odoo
 public | account_group                                               | table    | odoo
 public | account_group_id_seq                                        | sequence | odoo
 public | account_incoterms                                           | table    | odoo
 public | account_incoterms_id_seq                                    | sequence | odoo
 public | account_invoice_transaction_rel                             | table    | odoo
 public | account_journal                                             | table    | odoo
 public | account_journal_account_journal_group_rel                   | table    | odoo
 public | account_journal_account_reconcile_model_rel                 | table    | odoo
 public | account_journal_group                                       | table    | odoo
 public | account_journal_group_id_seq                                | sequence | odoo
 public | account_journal_id_seq                                      | sequence | odoo
 public | account_lock_exception                                      | table    | odoo
 public | account_lock_exception_id_seq                               | sequence | odoo
 public | account_merge_wizard                                        | table    | odoo
 public | account_merge_wizard_id_seq                                 | sequence | odoo
 public | account_merge_wizard_line                                   | table    | odoo
 public | account_merge_wizard_line_id_seq                            | sequence | odoo
 public | account_missing_transaction_wizard                          | table    | odoo
 public | account_missing_transaction_wizard_id_seq                   | sequence | odoo
 public | account_move                                                | table    | odoo
 public | account_move__account_payment                               | table    | odoo
 public | account_move_account_move_send_batch_wizard_rel             | table    | odoo
 public | account_move_account_resequence_wizard_rel                  | table    | odoo
 public | account_move_deferred_rel                                   | table    | odoo
 public | account_move_id_seq                                         | sequence | odoo
 public | account_move_line                                           | table    | odoo
 public | account_move_line_account_reconcile_wizard_rel              | table    | odoo
 public | account_move_line_account_tax_rel                           | table    | odoo
 public | account_move_line_id_seq                                    | sequence | odoo
 public | account_move_reversal                                       | table    | odoo
 public | account_move_reversal_id_seq                                | sequence | odoo
 public | account_move_reversal_move                                  | table    | odoo
 public | account_move_reversal_new_move                              | table    | odoo
 public | account_move_send_batch_wizard                              | table    | odoo
 public | account_move_send_batch_wizard_id_seq                       | sequence | odoo
 public | account_move_send_wizard                                    | table    | odoo
 public | account_move_send_wizard_id_seq                             | sequence | odoo
 public | account_move_send_wizard_res_partner_rel                    | table    | odoo
 public | account_move_validate_account_move_rel                      | table    | odoo
 public | account_multicurrency_revaluation_wizard                    | table    | odoo
 public | account_multicurrency_revaluation_wizard_id_seq             | sequence | odoo
 public | account_online_account                                      | table    | odoo
 public | account_online_account_id_seq                               | sequence | odoo
 public | account_online_link                                         | table    | odoo
 public | account_online_link_id_seq                                  | sequence | odoo
 public | account_partial_reconcile                                   | table    | odoo
 public | account_partial_reconcile_id_seq                            | sequence | odoo
 public | account_payment                                             | table    | odoo
 public | account_payment_account_bank_statement_line_rel             | table    | odoo
 public | account_payment_id_seq                                      | sequence | odoo
 public | account_payment_method                                      | table    | odoo
 public | account_payment_method_id_seq                               | sequence | odoo
 public | account_payment_method_line                                 | table    | odoo
 public | account_payment_method_line_id_seq                          | sequence | odoo
 public | account_payment_register                                    | table    | odoo
 public | account_payment_register_id_seq                             | sequence | odoo
 public | account_payment_register_move_line_rel                      | table    | odoo
 public | account_payment_term                                        | table    | odoo
 public | account_payment_term_id_seq                                 | sequence | odoo
 public | account_payment_term_line                                   | table    | odoo
 public | account_payment_term_line_id_seq                            | sequence | odoo
 public | account_reconcile_model                                     | table    | odoo
 public | account_reconcile_model_id_seq                              | sequence | odoo
 public | account_reconcile_model_line                                | table    | odoo
 public | account_reconcile_model_line_account_tax_rel                | table    | odoo
 public | account_reconcile_model_line_id_seq                         | sequence | odoo
 public | account_reconcile_model_res_partner_rel                     | table    | odoo
 public | account_reconcile_wizard                                    | table    | odoo
 public | account_reconcile_wizard_id_seq                             | sequence | odoo
 public | account_report                                              | table    | odoo
 public | account_report_account_report_horizontal_group_rel          | table    | odoo
 public | account_report_annotation                                   | table    | odoo
 public | account_report_annotation_id_seq                            | sequence | odoo
 public | account_report_budget                                       | table    | odoo
 public | account_report_budget_id_seq                                | sequence | odoo
 public | account_report_budget_item                                  | table    | odoo
 public | account_report_budget_item_id_seq                           | sequence | odoo
 public | account_report_column                                       | table    | odoo
 public | account_report_column_id_seq                                | sequence | odoo
 public | account_report_expression                                   | table    | odoo
 public | account_report_expression_id_seq                            | sequence | odoo
 public | account_report_external_value                               | table    | odoo
 public | account_report_external_value_id_seq                        | sequence | odoo
 public | account_report_file_download_error_wizard                   | table    | odoo
 public | account_report_file_download_error_wizard_id_seq            | sequence | odoo
 public | account_report_horizontal_group                             | table    | odoo
 public | account_report_horizontal_group_id_seq                      | sequence | odoo
 public | account_report_horizontal_group_rule                        | table    | odoo
 public | account_report_horizontal_group_rule_id_seq                 | sequence | odoo
 public | account_report_id_seq                                       | sequence | odoo
 public | account_report_line                                         | table    | odoo
 public | account_report_line_id_seq                                  | sequence | odoo
 public | account_report_section_rel                                  | table    | odoo
 public | account_report_send                                         | table    | odoo
 public | account_report_send_id_seq                                  | sequence | odoo
 public | account_report_send_res_partner_rel                         | table    | odoo
 public | account_reports_export_wizard                               | table    | odoo
 public | account_reports_export_wizard_format                        | table    | odoo
 public | account_reports_export_wizard_format_id_seq                 | sequence | odoo
 public | account_reports_export_wizard_id_seq                        | sequence | odoo
 public | account_resequence_wizard                                   | table    | odoo
 public | account_resequence_wizard_id_seq                            | sequence | odoo
 public | account_return                                              | table    | odoo
 public | account_return_check                                        | table    | odoo
 public | account_return_check_id_seq                                 | sequence | odoo
 public | account_return_check_ir_attachment_rel                      | table    | odoo
 public | account_return_check_res_users_rel                          | table    | odoo
 public | account_return_check_template                               | table    | odoo
 public | account_return_check_template_id_seq                        | sequence | odoo
 public | account_return_check_template_res_country_rel               | table    | odoo
 public | account_return_creation_wizard                              | table    | odoo
 public | account_return_creation_wizard_id_seq                       | sequence | odoo
 public | account_return_id_seq                                       | sequence | odoo
 public | account_return_ir_attachment_rel                            | table    | odoo
 public | account_return_payment_wizard                               | table    | odoo
 public | account_return_payment_wizard_id_seq                        | sequence | odoo
 public | account_return_res_company_rel                              | table    | odoo
 public | account_return_submission_wizard                            | table    | odoo
 public | account_return_submission_wizard_id_seq                     | sequence | odoo
 public | account_return_type                                         | table    | odoo
 public | account_return_type_id_seq                                  | sequence | odoo
 public | account_secure_entries_wizard                               | table    | odoo
 public | account_secure_entries_wizard_id_seq                        | sequence | odoo
 public | account_setup_bank_manual_config                            | table    | odoo
 public | account_setup_bank_manual_config_id_seq                     | sequence | odoo
 public | account_tax                                                 | table    | odoo
 public | account_tax_alternatives                                    | table    | odoo
 public | account_tax_filiation_rel                                   | table    | odoo
 public | account_tax_group                                           | table    | odoo
 public | account_tax_group_id_seq                                    | sequence | odoo
 public | account_tax_id_seq                                          | sequence | odoo
 public | account_tax_repartition_line                                | table    | odoo
 public | account_tax_repartition_line_id_seq                         | sequence | odoo
 public | account_tax_unit                                            | table    | odoo
 public | account_tax_unit_id_seq                                     | sequence | odoo
 public | account_tax_unit_res_company_rel                            | table    | odoo
 public | activity_attachment_rel                                     | table    | odoo
 public | adjusting_entries__account_move                             | table    | odoo
 public | auth_passkey_key                                            | table    | odoo
 public | auth_passkey_key_create                                     | table    | odoo
 public | auth_passkey_key_create_id_seq                              | sequence | odoo
 public | auth_passkey_key_id_seq                                     | sequence | odoo
 public | auth_totp_device                                            | table    | odoo
 public | auth_totp_device_id_seq                                     | sequence | odoo
 public | auth_totp_rate_limit_log                                    | table    | odoo
 public | auth_totp_rate_limit_log_id_seq                             | sequence | odoo
 public | auth_totp_wizard                                            | table    | odoo
 public | auth_totp_wizard_id_seq                                     | sequence | odoo
 public | base_document_layout                                        | table    | odoo
 public | base_document_layout_id_seq                                 | sequence | odoo
 public | base_enable_profiling_wizard                                | table    | odoo
 public | base_enable_profiling_wizard_id_seq                         | sequence | odoo
 public | base_import_import                                          | table    | odoo
 public | base_import_import_id_seq                                   | sequence | odoo
 public | base_import_mapping                                         | table    | odoo
 public | base_import_mapping_id_seq                                  | sequence | odoo
 public | base_import_module                                          | table    | odoo
 public | base_import_module_id_seq                                   | sequence | odoo
 public | base_language_export                                        | table    | odoo
 public | base_language_export_id_seq                                 | sequence | odoo
 public | base_language_import                                        | table    | odoo
 public | base_language_import_id_seq                                 | sequence | odoo
 public | base_language_install                                       | table    | odoo
 public | base_language_install_id_seq                                | sequence | odoo
 public | base_module_install_request                                 | table    | odoo
 public | base_module_install_request_id_seq                          | sequence | odoo
 public | base_module_install_review                                  | table    | odoo
 public | base_module_install_review_id_seq                           | sequence | odoo
 public | base_module_uninstall                                       | table    | odoo
 public | base_module_uninstall_id_seq                                | sequence | odoo
 public | base_module_uninstall_ir_module_module_rel                  | table    | odoo
 public | base_module_update                                          | table    | odoo
 public | base_module_update_id_seq                                   | sequence | odoo
 public | base_module_upgrade                                         | table    | odoo
 public | base_module_upgrade_id_seq                                  | sequence | odoo
 public | base_partner_merge_automatic_wizard                         | table    | odoo
 public | base_partner_merge_automatic_wizard_id_seq                  | sequence | odoo
 public | base_partner_merge_automatic_wizard_res_partner_rel         | table    | odoo
 public | base_partner_merge_line                                     | table    | odoo
 public | base_partner_merge_line_id_seq                              | sequence | odoo
 public | bus_bus                                                     | table    | odoo
 public | bus_bus_id_seq                                              | sequence | odoo
 public | change_password_own                                         | table    | odoo
 public | change_password_own_id_seq                                  | sequence | odoo
 public | change_password_user                                        | table    | odoo
 public | change_password_user_id_seq                                 | sequence | odoo
 public | change_password_wizard                                      | table    | odoo
 public | change_password_wizard_id_seq                               | sequence | odoo
 public | decimal_precision                                           | table    | odoo
 public | decimal_precision_id_seq                                    | sequence | odoo
 public | digest_digest                                               | table    | odoo
 public | digest_digest_id_seq                                        | sequence | odoo
 public | digest_digest_res_users_rel                                 | table    | odoo
 public | digest_tip                                                  | table    | odoo
 public | digest_tip_id_seq                                           | sequence | odoo
 public | digest_tip_res_users_rel                                    | table    | odoo
 public | discuss_call_history                                        | table    | odoo
 public | discuss_call_history_id_seq                                 | sequence | odoo
 public | discuss_channel                                             | table    | odoo
 public | discuss_channel_id_seq                                      | sequence | odoo
 public | discuss_channel_member                                      | table    | odoo
 public | discuss_channel_member_id_seq                               | sequence | odoo
 public | discuss_channel_res_groups_rel                              | table    | odoo
 public | discuss_channel_rtc_session                                 | table    | odoo
 public | discuss_channel_rtc_session_id_seq                          | sequence | odoo
 public | discuss_gif_favorite                                        | table    | odoo
 public | discuss_gif_favorite_id_seq                                 | sequence | odoo
 public | discuss_voice_metadata                                      | table    | odoo
 public | discuss_voice_metadata_id_seq                               | sequence | odoo
 public | dms_acc_rep_export_wizard_format_rel                        | table    | odoo
 public | email_template_attachment_rel                               | table    | odoo
 public | estate_property                                             | table    | odoo
 public | estate_property_estate_property_tag_rel                     | table    | odoo
 public | estate_property_id_seq                                      | sequence | odoo
 public | estate_property_issue                                       | table    | odoo
 public | estate_property_issue_id_seq                                | sequence | odoo
 public | estate_property_offer                                       | table    | odoo
 public | estate_property_offer_id_seq                                | sequence | odoo
 public | estate_property_tag                                         | table    | odoo
 public | estate_property_tag_id_seq                                  | sequence | odoo
 public | estate_property_type                                        | table    | odoo
 public | estate_property_type_id_seq                                 | sequence | odoo
 public | estate_property_visit                                       | table    | odoo
 public | estate_property_visit_id_seq                                | sequence | odoo
 public | fetchmail_server                                            | table    | odoo
 public | fetchmail_server_id_seq                                     | sequence | odoo
 public | html_editor_converter_test                                  | table    | odoo
 public | html_editor_converter_test_id_seq                           | sequence | odoo
 public | html_editor_converter_test_sub                              | table    | odoo
 public | html_editor_converter_test_sub_id_seq                       | sequence | odoo
 public | iap_account                                                 | table    | odoo
 public | iap_account_id_seq                                          | sequence | odoo
 public | iap_account_res_company_rel                                 | table    | odoo
 public | iap_account_res_users_rel                                   | table    | odoo
 public | iap_service                                                 | table    | odoo
 public | iap_service_id_seq                                          | sequence | odoo
 public | ir_act_client                                               | table    | odoo
 public | ir_act_report_xml                                           | table    | odoo
 public | ir_act_server                                               | table    | odoo
 public | ir_act_server_group_rel                                     | table    | odoo
 public | ir_act_server_res_partner_rel                               | table    | odoo
 public | ir_act_server_webhook_field_rel                             | table    | odoo
 public | ir_act_url                                                  | table    | odoo
 public | ir_act_window                                               | table    | odoo
 public | ir_act_window_group_rel                                     | table    | odoo
 public | ir_act_window_view                                          | table    | odoo
 public | ir_act_window_view_id_seq                                   | sequence | odoo
 public | ir_actions                                                  | table    | odoo
 public | ir_actions_id_seq                                           | sequence | odoo
 public | ir_actions_server_history                                   | table    | odoo
 public | ir_actions_server_history_id_seq                            | sequence | odoo
 public | ir_actions_todo                                             | table    | odoo
 public | ir_actions_todo_id_seq                                      | sequence | odoo
 public | ir_asset                                                    | table    | odoo
 public | ir_asset_id_seq                                             | sequence | odoo
 public | ir_attachment                                               | table    | odoo
 public | ir_attachment_id_seq                                        | sequence | odoo
 public | ir_config_parameter                                         | table    | odoo
 public | ir_config_parameter_id_seq                                  | sequence | odoo
 public | ir_cron                                                     | table    | odoo
 public | ir_cron_id_seq                                              | sequence | odoo
 public | ir_cron_progress                                            | table    | odoo
 public | ir_cron_progress_id_seq                                     | sequence | odoo
 public | ir_cron_trigger                                             | table    | odoo
 public | ir_cron_trigger_id_seq                                      | sequence | odoo
 public | ir_default                                                  | table    | odoo
 public | ir_default_id_seq                                           | sequence | odoo
 public | ir_demo                                                     | table    | odoo
 public | ir_demo_failure                                             | table    | odoo
 public | ir_demo_failure_id_seq                                      | sequence | odoo
 public | ir_demo_failure_wizard                                      | table    | odoo
 public | ir_demo_failure_wizard_id_seq                               | sequence | odoo
 public | ir_demo_id_seq                                              | sequence | odoo
 public | ir_embedded_actions                                         | table    | odoo
 public | ir_embedded_actions_id_seq                                  | sequence | odoo
 public | ir_embedded_actions_res_groups_rel                          | table    | odoo
 public | ir_exports                                                  | table    | odoo
 public | ir_exports_id_seq                                           | sequence | odoo
 public | ir_exports_line                                             | table    | odoo
 public | ir_exports_line_id_seq                                      | sequence | odoo
 public | ir_filters                                                  | table    | odoo
 public | ir_filters_id_seq                                           | sequence | odoo
 public | ir_filters_res_users_rel                                    | table    | odoo
 public | ir_logging                                                  | table    | odoo
 public | ir_logging_id_seq                                           | sequence | odoo
 public | ir_mail_server                                              | table    | odoo
 public | ir_mail_server_id_seq                                       | sequence | odoo
 public | ir_model                                                    | table    | odoo
 public | ir_model_access                                             | table    | odoo
 public | ir_model_access_id_seq                                      | sequence | odoo
 public | ir_model_constraint                                         | table    | odoo
 public | ir_model_constraint_id_seq                                  | sequence | odoo
 public | ir_model_data                                               | table    | odoo
 public | ir_model_data_id_seq                                        | sequence | odoo
 public | ir_model_fields                                             | table    | odoo
 public | ir_model_fields_group_rel                                   | table    | odoo
 public | ir_model_fields_id_seq                                      | sequence | odoo
 public | ir_model_fields_selection                                   | table    | odoo
 public | ir_model_fields_selection_id_seq                            | sequence | odoo
 public | ir_model_id_seq                                             | sequence | odoo
 public | ir_model_inherit                                            | table    | odoo
 public | ir_model_inherit_id_seq                                     | sequence | odoo
 public | ir_model_relation                                           | table    | odoo
 public | ir_model_relation_id_seq                                    | sequence | odoo
 public | ir_model_spreadsheet_dashboard_rel                          | table    | odoo
 public | ir_module_category                                          | table    | odoo
 public | ir_module_category_id_seq                                   | sequence | odoo
 public | ir_module_module                                            | table    | odoo
 public | ir_module_module_dependency                                 | table    | odoo
 public | ir_module_module_dependency_id_seq                          | sequence | odoo
 public | ir_module_module_exclusion                                  | table    | odoo
 public | ir_module_module_exclusion_id_seq                           | sequence | odoo
 public | ir_module_module_id_seq                                     | sequence | odoo
 public | ir_profile                                                  | table    | odoo
 public | ir_profile_id_seq                                           | sequence | odoo
 public | ir_rule                                                     | table    | odoo
 public | ir_rule_id_seq                                              | sequence | odoo
 public | ir_sequence                                                 | table    | odoo
 public | ir_sequence_002                                             | sequence | odoo
 public | ir_sequence_date_range                                      | table    | odoo
 public | ir_sequence_date_range_id_seq                               | sequence | odoo
 public | ir_sequence_id_seq                                          | sequence | odoo
 public | ir_ui_menu                                                  | table    | odoo
 public | ir_ui_menu_group_rel                                        | table    | odoo
 public | ir_ui_menu_id_seq                                           | sequence | odoo
 public | ir_ui_view                                                  | table    | odoo
 public | ir_ui_view_custom                                           | table    | odoo
 public | ir_ui_view_custom_id_seq                                    | sequence | odoo
 public | ir_ui_view_group_rel                                        | table    | odoo
 public | ir_ui_view_id_seq                                           | sequence | odoo
 public | mail_activity                                               | table    | odoo
 public | mail_activity_id_seq                                        | sequence | odoo
 public | mail_activity_plan                                          | table    | odoo
 public | mail_activity_plan_id_seq                                   | sequence | odoo
 public | mail_activity_plan_mail_activity_schedule_rel               | table    | odoo
 public | mail_activity_plan_template                                 | table    | odoo
 public | mail_activity_plan_template_id_seq                          | sequence | odoo
 public | mail_activity_plan_template_mail_activity_type_rel          | table    | odoo
 public | mail_activity_rel                                           | table    | odoo
 public | mail_activity_schedule                                      | table    | odoo
 public | mail_activity_schedule_id_seq                               | sequence | odoo
 public | mail_activity_schedule_line                                 | table    | odoo
 public | mail_activity_schedule_line_id_seq                          | sequence | odoo
 public | mail_activity_type                                          | table    | odoo
 public | mail_activity_type_id_seq                                   | sequence | odoo
 public | mail_activity_type_mail_template_rel                        | table    | odoo
 public | mail_alias                                                  | table    | odoo
 public | mail_alias_domain                                           | table    | odoo
 public | mail_alias_domain_id_seq                                    | sequence | odoo
 public | mail_alias_id_seq                                           | sequence | odoo
 public | mail_blacklist                                              | table    | odoo
 public | mail_blacklist_id_seq                                       | sequence | odoo
 public | mail_blacklist_remove                                       | table    | odoo
 public | mail_blacklist_remove_id_seq                                | sequence | odoo
 public | mail_canned_response                                        | table    | odoo
 public | mail_canned_response_id_seq                                 | sequence | odoo
 public | mail_canned_response_res_groups_rel                         | table    | odoo
 public | mail_compose_message                                        | table    | odoo
 public | mail_compose_message_id_seq                                 | sequence | odoo
 public | mail_compose_message_ir_attachments_rel                     | table    | odoo
 public | mail_compose_message_res_partner_rel                        | table    | odoo
 public | mail_followers                                              | table    | odoo
 public | mail_followers_edit                                         | table    | odoo
 public | mail_followers_edit_id_seq                                  | sequence | odoo
 public | mail_followers_edit_res_partner_rel                         | table    | odoo
 public | mail_followers_id_seq                                       | sequence | odoo
 public | mail_followers_mail_message_subtype_rel                     | table    | odoo
 public | mail_gateway_allowed                                        | table    | odoo
 public | mail_gateway_allowed_id_seq                                 | sequence | odoo
 public | mail_guest                                                  | table    | odoo
 public | mail_guest_id_seq                                           | sequence | odoo
 public | mail_ice_server                                             | table    | odoo
 public | mail_ice_server_id_seq                                      | sequence | odoo
 public | mail_link_preview                                           | table    | odoo
 public | mail_link_preview_id_seq                                    | sequence | odoo
 public | mail_mail                                                   | table    | odoo
 public | mail_mail_id_seq                                            | sequence | odoo
 public | mail_mail_res_partner_rel                                   | table    | odoo
 public | mail_message                                                | table    | odoo
 public | mail_message_id_seq                                         | sequence | odoo
 public | mail_message_link_preview                                   | table    | odoo
 public | mail_message_link_preview_id_seq                            | sequence | odoo
 public | mail_message_reaction                                       | table    | odoo
 public | mail_message_reaction_id_seq                                | sequence | odoo
 public | mail_message_res_partner_rel                                | table    | odoo
 public | mail_message_res_partner_starred_rel                        | table    | odoo
 public | mail_message_schedule                                       | table    | odoo
 public | mail_message_schedule_id_seq                                | sequence | odoo
 public | mail_message_subtype                                        | table    | odoo
 public | mail_message_subtype_id_seq                                 | sequence | odoo
 public | mail_message_translation                                    | table    | odoo
 public | mail_message_translation_id_seq                             | sequence | odoo
 public | mail_notification                                           | table    | odoo
 public | mail_notification_id_seq                                    | sequence | odoo
 public | mail_presence                                               | table    | odoo
 public | mail_presence_id_seq                                        | sequence | odoo
 public | mail_push                                                   | table    | odoo
 public | mail_push_device                                            | table    | odoo
 public | mail_push_device_id_seq                                     | sequence | odoo
 public | mail_push_id_seq                                            | sequence | odoo
 public | mail_scheduled_message                                      | table    | odoo
 public | mail_scheduled_message_id_seq                               | sequence | odoo
 public | mail_scheduled_message_res_partner_rel                      | table    | odoo
 public | mail_template                                               | table    | odoo
 public | mail_template_id_seq                                        | sequence | odoo
 public | mail_template_ir_actions_report_rel                         | table    | odoo
 public | mail_template_mail_template_reset_rel                       | table    | odoo
 public | mail_template_preview                                       | table    | odoo
 public | mail_template_preview_id_seq                                | sequence | odoo
 public | mail_template_reset                                         | table    | odoo
 public | mail_template_reset_id_seq                                  | sequence | odoo
 public | mail_tracking_value                                         | table    | odoo
 public | mail_tracking_value_id_seq                                  | sequence | odoo
 public | message_attachment_rel                                      | table    | odoo
 public | module_country                                              | table    | odoo
 public | onboarding_onboarding                                       | table    | odoo
 public | onboarding_onboarding_id_seq                                | sequence | odoo
 public | onboarding_onboarding_onboarding_onboarding_step_rel        | table    | odoo
 public | onboarding_onboarding_step                                  | table    | odoo
 public | onboarding_onboarding_step_id_seq                           | sequence | odoo
 public | onboarding_progress                                         | table    | odoo
 public | onboarding_progress_id_seq                                  | sequence | odoo
 public | onboarding_progress_onboarding_progress_step_rel            | table    | odoo
 public | onboarding_progress_step                                    | table    | odoo
 public | onboarding_progress_step_id_seq                             | sequence | odoo
 public | orm_signaling_assets                                        | table    | odoo
 public | orm_signaling_assets_id_seq                                 | sequence | odoo
 public | orm_signaling_default                                       | table    | odoo
 public | orm_signaling_default_id_seq                                | sequence | odoo
 public | orm_signaling_groups                                        | table    | odoo
 public | orm_signaling_groups_id_seq                                 | sequence | odoo
 public | orm_signaling_registry                                      | table    | odoo
 public | orm_signaling_registry_id_seq                               | sequence | odoo
 public | orm_signaling_routing                                       | table    | odoo
 public | orm_signaling_routing_id_seq                                | sequence | odoo
 public | orm_signaling_stable                                        | table    | odoo
 public | orm_signaling_stable_id_seq                                 | sequence | odoo
 public | orm_signaling_templates                                     | table    | odoo
 public | orm_signaling_templates_id_seq                              | sequence | odoo
 public | payment_capture_wizard                                      | table    | odoo
 public | payment_capture_wizard_id_seq                               | sequence | odoo
 public | payment_capture_wizard_payment_transaction_rel              | table    | odoo
 public | payment_country_rel                                         | table    | odoo
 public | payment_currency_rel                                        | table    | odoo
 public | payment_link_wizard                                         | table    | odoo
 public | payment_link_wizard_id_seq                                  | sequence | odoo
 public | payment_method                                              | table    | odoo
 public | payment_method_id_seq                                       | sequence | odoo
 public | payment_method_payment_provider_rel                         | table    | odoo
 public | payment_method_res_country_rel                              | table    | odoo
 public | payment_method_res_currency_rel                             | table    | odoo
 public | payment_provider                                            | table    | odoo
 public | payment_provider_id_seq                                     | sequence | odoo
 public | payment_refund_wizard                                       | table    | odoo
 public | payment_refund_wizard_id_seq                                | sequence | odoo
 public | payment_token                                               | table    | odoo
 public | payment_token_id_seq                                        | sequence | odoo
 public | payment_transaction                                         | table    | odoo
 public | payment_transaction_id_seq                                  | sequence | odoo
 public | phone_blacklist                                             | table    | odoo
 public | phone_blacklist_id_seq                                      | sequence | odoo
 public | phone_blacklist_remove                                      | table    | odoo
 public | phone_blacklist_remove_id_seq                               | sequence | odoo
 public | portal_share                                                | table    | odoo
 public | portal_share_id_seq                                         | sequence | odoo
 public | portal_share_res_partner_rel                                | table    | odoo
 public | portal_wizard                                               | table    | odoo
 public | portal_wizard_id_seq                                        | sequence | odoo
 public | portal_wizard_res_partner_rel                               | table    | odoo
 public | portal_wizard_user                                          | table    | odoo
 public | portal_wizard_user_id_seq                                   | sequence | odoo
 public | privacy_log                                                 | table    | odoo
 public | privacy_log_id_seq                                          | sequence | odoo
 public | privacy_lookup_wizard                                       | table    | odoo
 public | privacy_lookup_wizard_id_seq                                | sequence | odoo
 public | privacy_lookup_wizard_line                                  | table    | odoo
 public | privacy_lookup_wizard_line_id_seq                           | sequence | odoo
 public | product_attr_exclusion_value_ids_rel                        | table    | odoo
 public | product_attribute                                           | table    | odoo
 public | product_attribute_custom_value                              | table    | odoo
 public | product_attribute_custom_value_id_seq                       | sequence | odoo
 public | product_attribute_id_seq                                    | sequence | odoo
 public | product_attribute_product_template_rel                      | table    | odoo
 public | product_attribute_value                                     | table    | odoo
 public | product_attribute_value_id_seq                              | sequence | odoo
 public | product_attribute_value_product_template_attribute_line_rel | table    | odoo
 public | product_category                                            | table    | odoo
 public | product_category_id_seq                                     | sequence | odoo
 public | product_combo                                               | table    | odoo
 public | product_combo_id_seq                                        | sequence | odoo
 public | product_combo_item                                          | table    | odoo
 public | product_combo_item_id_seq                                   | sequence | odoo
 public | product_combo_product_template_rel                          | table    | odoo
 public | product_document                                            | table    | odoo
 public | product_document_id_seq                                     | sequence | odoo
 public | product_fetch_image_wizard                                  | table    | odoo
 public | product_fetch_image_wizard_id_seq                           | sequence | odoo
 public | product_fetch_image_wizard_product_product_rel              | table    | odoo
 public | product_label_layout                                        | table    | odoo
 public | product_label_layout_id_seq                                 | sequence | odoo
 public | product_label_layout_product_product_rel                    | table    | odoo
 public | product_label_layout_product_template_rel                   | table    | odoo
 public | product_pricelist                                           | table    | odoo
 public | product_pricelist_id_seq                                    | sequence | odoo
 public | product_pricelist_item                                      | table    | odoo
 public | product_pricelist_item_id_seq                               | sequence | odoo
 public | product_product                                             | table    | odoo
 public | product_product_id_seq                                      | sequence | odoo
 public | product_supplier_taxes_rel                                  | table    | odoo
 public | product_supplierinfo                                        | table    | odoo
 public | product_supplierinfo_id_seq                                 | sequence | odoo
 public | product_tag                                                 | table    | odoo
 public | product_tag_id_seq                                          | sequence | odoo
 public | product_tag_product_product_rel                             | table    | odoo
 public | product_tag_product_template_rel                            | table    | odoo
 public | product_taxes_rel                                           | table    | odoo
 public | product_template                                            | table    | odoo
 public | product_template_attribute_exclusion                        | table    | odoo
 public | product_template_attribute_exclusion_id_seq                 | sequence | odoo
 public | product_template_attribute_line                             | table    | odoo
 public | product_template_attribute_line_id_seq                      | sequence | odoo
 public | product_template_attribute_value                            | table    | odoo
 public | product_template_attribute_value_id_seq                     | sequence | odoo
 public | product_template_id_seq                                     | sequence | odoo
 public | product_template_uom_uom_rel                                | table    | odoo
 public | product_uom                                                 | table    | odoo
 public | product_uom_id_seq                                          | sequence | odoo
 public | product_variant_combination                                 | table    | odoo
 public | properties_base_definition                                  | table    | odoo
 public | properties_base_definition_id_seq                           | sequence | odoo
 public | qr_code_payment_wizard                                      | table    | odoo
 public | qr_code_payment_wizard_id_seq                               | sequence | odoo
 public | rel_followup_manual_reminder_res_partner                    | table    | odoo
 public | rel_modules_langexport                                      | table    | odoo
 public | report_layout                                               | table    | odoo
 public | report_layout_id_seq                                        | sequence | odoo
 public | report_paperformat                                          | table    | odoo
 public | report_paperformat_id_seq                                   | sequence | odoo
 public | res_bank                                                    | table    | odoo
 public | res_bank_id_seq                                             | sequence | odoo
 public | res_company                                                 | table    | odoo
 public | res_company_id_seq                                          | sequence | odoo
 public | res_company_spreadsheet_dashboard_rel                       | table    | odoo
 public | res_company_users_rel                                       | table    | odoo
 public | res_config                                                  | table    | odoo
 public | res_config_id_seq                                           | sequence | odoo
 public | res_config_settings                                         | table    | odoo
 public | res_config_settings_id_seq                                  | sequence | odoo
 public | res_country                                                 | table    | odoo
 public | res_country_group                                           | table    | odoo
 public | res_country_group_id_seq                                    | sequence | odoo
 public | res_country_group_pricelist_rel                             | table    | odoo
 public | res_country_group_res_country_state_rel                     | table    | odoo
 public | res_country_id_seq                                          | sequence | odoo
 public | res_country_res_country_group_rel                           | table    | odoo
 public | res_country_state                                           | table    | odoo
 public | res_country_state_id_seq                                    | sequence | odoo
 public | res_currency                                                | table    | odoo
 public | res_currency_id_seq                                         | sequence | odoo
 public | res_currency_rate                                           | table    | odoo
 public | res_currency_rate_id_seq                                    | sequence | odoo
 public | res_device                                                  | view     | odoo
 public | res_device_log                                              | table    | odoo
 public | res_device_log_id_seq                                       | sequence | odoo
 public | res_groups                                                  | table    | odoo
 public | res_groups_id_seq                                           | sequence | odoo
 public | res_groups_implied_rel                                      | table    | odoo
 public | res_groups_privilege                                        | table    | odoo
 public | res_groups_privilege_id_seq                                 | sequence | odoo
 public | res_groups_report_rel                                       | table    | odoo
 public | res_groups_spreadsheet_dashboard_rel                        | table    | odoo
 public | res_groups_users_rel                                        | table    | odoo
 public | res_lang                                                    | table    | odoo
 public | res_lang_id_seq                                             | sequence | odoo
 public | res_lang_install_rel                                        | table    | odoo
 public | res_partner                                                 | table    | odoo
 public | res_partner_bank                                            | table    | odoo
 public | res_partner_bank_id_seq                                     | sequence | odoo
 public | res_partner_category                                        | table    | odoo
 public | res_partner_category_id_seq                                 | sequence | odoo
 public | res_partner_id_seq                                          | sequence | odoo
 public | res_partner_industry                                        | table    | odoo
 public | res_partner_industry_id_seq                                 | sequence | odoo
 public | res_partner_res_partner_category_rel                        | table    | odoo
 public | res_role                                                    | table    | odoo
 public | res_role_id_seq                                             | sequence | odoo
 public | res_role_res_users_rel                                      | table    | odoo
 public | res_users                                                   | table    | odoo
 public | res_users_apikeys                                           | table    | odoo
 public | res_users_apikeys_description                               | table    | odoo
 public | res_users_apikeys_description_id_seq                        | sequence | odoo
 public | res_users_apikeys_id_seq                                    | sequence | odoo
 public | res_users_deletion                                          | table    | odoo
 public | res_users_deletion_id_seq                                   | sequence | odoo
 public | res_users_id_seq                                            | sequence | odoo
 public | res_users_identitycheck                                     | table    | odoo
 public | res_users_identitycheck_id_seq                              | sequence | odoo
 public | res_users_log                                               | table    | odoo
 public | res_users_log_id_seq                                        | sequence | odoo
 public | res_users_settings                                          | table    | odoo
 public | res_users_settings_embedded_action                          | table    | odoo
 public | res_users_settings_embedded_action_id_seq                   | sequence | odoo
 public | res_users_settings_id_seq                                   | sequence | odoo
 public | res_users_settings_volumes                                  | table    | odoo
 public | res_users_settings_volumes_id_seq                           | sequence | odoo
 public | res_users_spreadsheet_dashboard_rel                         | table    | odoo
 public | res_users_web_tour_tour_rel                                 | table    | odoo
 public | reset_view_arch_wizard                                      | table    | odoo
 public | reset_view_arch_wizard_id_seq                               | sequence | odoo
 public | resource_calendar                                           | table    | odoo
 public | resource_calendar_attendance                                | table    | odoo
 public | resource_calendar_attendance_id_seq                         | sequence | odoo
 public | resource_calendar_id_seq                                    | sequence | odoo
 public | resource_calendar_leaves                                    | table    | odoo
 public | resource_calendar_leaves_id_seq                             | sequence | odoo
 public | resource_resource                                           | table    | odoo
 public | resource_resource_id_seq                                    | sequence | odoo
 public | rule_group_rel                                              | table    | odoo
 public | scheduled_message_attachment_rel                            | table    | odoo
 public | server_action_history_wizard                                | table    | odoo
 public | server_action_history_wizard_id_seq                         | sequence | odoo
 public | sms_account_code                                            | table    | odoo
 public | sms_account_code_id_seq                                     | sequence | odoo
 public | sms_account_phone                                           | table    | odoo
 public | sms_account_phone_id_seq                                    | sequence | odoo
 public | sms_account_sender                                          | table    | odoo
 public | sms_account_sender_id_seq                                   | sequence | odoo
 public | sms_composer                                                | table    | odoo
 public | sms_composer_id_seq                                         | sequence | odoo
 public | sms_sms                                                     | table    | odoo
 public | sms_sms_id_seq                                              | sequence | odoo
 public | sms_template                                                | table    | odoo
 public | sms_template_id_seq                                         | sequence | odoo
 public | sms_template_preview                                        | table    | odoo
 public | sms_template_preview_id_seq                                 | sequence | odoo
 public | sms_template_reset                                          | table    | odoo
 public | sms_template_reset_id_seq                                   | sequence | odoo
 public | sms_template_sms_template_reset_rel                         | table    | odoo
 public | sms_tracker                                                 | table    | odoo
 public | sms_tracker_id_seq                                          | sequence | odoo
 public | snailmail_letter                                            | table    | odoo
 public | snailmail_letter_id_seq                                     | sequence | odoo
 public | spreadsheet_cell_thread                                     | table    | odoo
 public | spreadsheet_cell_thread_id_seq                              | sequence | odoo
 public | spreadsheet_dashboard                                       | table    | odoo
 public | spreadsheet_dashboard_group                                 | table    | odoo
 public | spreadsheet_dashboard_group_id_seq                          | sequence | odoo
 public | spreadsheet_dashboard_id_seq                                | sequence | odoo
 public | spreadsheet_dashboard_share                                 | table    | odoo
 public | spreadsheet_dashboard_share_id_seq                          | sequence | odoo
 public | spreadsheet_revision                                        | table    | odoo
 public | spreadsheet_revision_id_seq                                 | sequence | odoo
 public | uom_uom                                                     | table    | odoo
 public | uom_uom_id_seq                                              | sequence | odoo
 public | update_product_attribute_value                              | table    | odoo
 public | update_product_attribute_value_id_seq                       | sequence | odoo
 public | validate_account_move                                       | table    | odoo
 public | validate_account_move_id_seq                                | sequence | odoo
 public | web_tour_tour                                               | table    | odoo
 public | web_tour_tour_id_seq                                        | sequence | odoo
 public | web_tour_tour_step                                          | table    | odoo
 public | web_tour_tour_step_id_seq                                   | sequence | odoo
 public | wizard_ir_model_menu_create                                 | table    | odoo
 public | wizard_ir_model_menu_create_id_seq                          | sequence | odoo
(739 rows)

