# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Assume Python 3.12
target-version = "py312"

line-length = 255 
[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
select = ["ALL"]
ignore = ["A","ARG","ANN","B","C901","D","DTZ","E501","ERA001","FBT","N","PD","PERF","PIE790","PLR","PT","Q","RSE102","RUF001","RUF012","S","SIM102","SIM108","SLF001","TID252","UP031","TRY003","TRY300","UP038","E713","SIM117","PGH003","RUF005","FIX","TD","TRY400","C408","PLW2901","PTH","EM102","INP001","CPY001","E266","PIE808","PLC2701","RUF100","FA100","FURB","COM812","TRY002","B904","EM101","I001","UP006","UP007","RET","RUF021","E741","ASYNC","AIR","DJ","NPY","FA102","F401"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = ["A","ARG","ANN","B","C901","D","DTZ","E501","ERA001","FBT","N","PD","PERF","PIE790","PLR","PT","Q","RSE102","RUF001","RUF012","S","SIM102","SIM108","SLF001","TID252","UP031","TRY003","TRY300","UP038","E713","SIM117","PGH003","RUF005","FIX","TD","TRY400","C408","PLW2901","PTH","EM102","INP001","CPY001","E266","PIE808","PLC2701","RUF100","FA100","FURB","COM812","TRY002","B904","EM101","I001","UP006","UP007","RET","RUF021","E741","ASYNC","AIR","DJ","NPY","FA102","F401"]
