{
    "name": "ecommerce purchase",
    "category": "Website",
    "depends": [
        "website_sale",
        "sale",
        "website",
        "auth_signup",
        "product",
        "purchase",
        "sale_management",
        "portal",
    ],
    "data": [
        "security/security.xml",
        "views/auth_signup_web_sale_purchase_view.xml",
        "views/res_config_settings_views.xml",
        "views/product_template_view.xml",
        "views/dashboard_template.xml",
        "views/add_product.xml",
        "views/product_template_dashboard_view.xml",
        "views/seller_portal.xml",
        "views/purchase_portal.xml",
        "views/purchase_order_portal.xml",
    ],
    "installable": True,
    "application": True,
    "author": "RADHR",
    "license": "LGPL-3",
}
