{
    'name': "Real Estate",
    'version': '1.0',
    'depends': ['base', 'mail', 'website'],
    'author': "Himilsinh Sindha (hisi)",
    'category': 'Real Estate/Brokerage',
    'description': "Real Estate Properties Management",
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'data': [
        'security/estate_property_groups.xml',
        'security/ir.model.access.csv',
        'security/estate_property_security.xml',
        'report/estate_property_templates.xml',
        'report/estate_property_reports.xml',
        'views/estate_property_views.xml',
        'views/estate_property_type_views.xml',
        'views/estate_property_tag_views.xml',
        'views/estate_property_offer_views.xml',
        'views/res_users_views.xml',
        'views/estate_property_menus.xml',
        'views/estate_website_templates.xml',
        'data/estate_property_data.xml',
        'wizard/estate_property_wizard_view.xml',
    ],
    'demo': [
        'demo/estate_property_demo.xml',
    ],
}
