{
    'name': 'dental',
    'version': '1.0',
    'summary': 'dental management system',
    'description': 'A module for managing dental problems and related entities.',
    'category': 'website',
    'author': 'YASP',
    'sequence': 1,
    'depends': ['base', 'website', 'mail', 'account'],
    'license': 'LGPL-3',
    'data': [
        'security/ir.model.access.csv',
        'views/dental_portal_templates.xml',
        'views/dental_views.xml',
        'views/medical_aids_views.xml',
        'views/medical_symptoms_views.xml',
        'views/medication_views.xml',
        'views/dental_patient_history_views.xml',
        'views/dental_menu.xml',
    ],
    'installable': True,
    'application': True,
}
