{
    "name": "Freight MD",
    "version": "1.0",
    "summary": "Module for managing freight",
    "description": """
        Freight MD Module
    """,
    "category": "services/freight md",
    "author": "Krishil Modh",
    "depends": ["base", "account"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/partner_type_views.xml",
        "views/freight_tags_views.xml",
        "views/document_type_views.xml",
        "views/commodity_req_views.xml",
        "views/commodity_group_views.xml",
        "views/commodity_views.xml",
        "views/account_incoterms_views.xml",
        "views/service_scope_views.xml",
        "views/clearance_type_views.xml",
        "views/tracking_stage_views.xml",
        "views/activity_type_views.xml",
        "views/flight_views.xml",
        "views/vessel_views.xml",
        "views/ocean_shipment_scope_views.xml",
        "views/bill_of_lading_type_views.xml",
        "views/container_views.xml",
        "views/container_type_views.xml",
        "views/transport_type_views.xml",
        "views/package_type_views.xml",
        "views/freight_md_views.xml",
        "views/freight_md_menus.xml",
    ],
    "installable": True,
    "application": True,
    "license": "AGPL-3",
}
