{
    'name': "freight-data",
    'version': "1.0",
    'depends': ["base", "account"],
    'author': "Dhruv",
    'category': "Services/Freight MD",
    'application': True,
    'installable': True,
    'description': """
    Module for the practice and getting knowledge in the technicality
    """,
    'data': [
        'security/freight_security.xml',
        'security/ir.model.access.csv',
        'data/is_options_data.xml',
        'views/freight_locations_ports_cities_views.xml',
        'views/freight_locations_countries_views.xml',
        'views/freight_locations_country_group_views.xml',
        'views/freight_settings_freight_type_views.xml',
        'views/freight_settings_package_type_views.xml',
        'views/freight_settings_container_type_views.xml',
        'views/freight_settings_containers_views.xml',
        'views/freight_settings_bill_of_lading_type_views.xml',
        'views/freight_settings_ocean_shipments_scope_views.xml',
        'views/freight_settings_vessels_views.xml',
        'views/freight_settings_flights_views.xml',
        'views/freight_service_settings_service_scope_views.xml',
        'views/freight_service_settings_clearance_type_views.xml',
        'views/freight_service_settings_tracking_stages_views.xml',
        'views/freight_service_settings_activity_type_views.xml',
        'views/freight_service_settings_incoterms_views.xml',
        'views/freight_configuration_commodity_group_views.xml',
        'views/freight_configuration_commodity_data_views.xml',
        'views/freight_configuration_partner_type_views.xml',
        'views/freight_configuration_documents_types_views.xml',
        'views/freight_configuration_freight_tags_views.xml',
        'views/freight_menus.xml',
    ],
    'demo': [],
    'license': 'AGPL-3',
}
