{
    'name': 'Freight Data',
    'version': '1.0',
    'depends': ['base', 'account'],
    'author': 'NIAD',
    'category': 'frieght operations',
    'description': 'Module for managing freight data',
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/freight_locations_countries_views.xml',
        'views/freight_locations_country_group_views.xml',
        'views/freight_locations_port_cities_views.xml',
        'data/freight_selection_data.xml',
        'views/freight_settings_freight_type_views.xml',
        'views/freight_settings_package_type_views.xml',
        'data/package_selection_data.xml',
        'views/freight_settings_container_type_views.xml',
        'views/freight_settings_containers_views.xml',
        'views/freight_settings_bill_of_lading_type_views.xml',
        'views/freight_settings_ocean_shipments_scope_views.xml',
        'views/freight_settings_vessels_views.xml',
        'views/freight_settings_flights_views.xml',
        'views/freight_service_scope_views.xml',
        'views/freight_service_clearance_type_views.xml',
        'views/freight_service_incoterms_views.xml',
        'views/freight_service_tracking_stages_views.xml',
        'views/freight_service_activity_type_views.xml',
        'views/freight_configuration_commodity_group_views.xml',
        'views/freight_configuration_commodity_data_views.xml',
        'data/commodity_request_data.xml',
        'views/freight_configuration_partner_type_views.xml',
        'views/freight_configuration_document_types_views.xml',
        'views/freight_configuration_freight_tags_views.xml',
        'views/freight_data_menus.xml',
    ],
    'demo': [],
    'application': True,
    'installable': True,
    'license': 'AGPL-3',
}
