{
    'name': "Freight Data",
    'description': """
        Manage Ports Information
    """,
    'author': "Sourabh",
    'category': 'services/freight_data',
    'version': '0.1',
    'application': True,
    'installable': True,
    'depends': ["base", "account"],
    'images': ["static/description/freight.png"],
    'data': [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/data.xml",
        "views/freight_is_port_view.xml",
        "views/freight_is_package_view.xml",
        "views/partner_type_view.xml",
        "views/freight_tags_view.xml",
        "views/document_type_view.xml",
        "views/commodity_view.xml",
        "views/commodity_group_view.xml",
        "views/activity_type_view.xml",
        "views/tracking_stages_view.xml",
        "views/clearance_types_view.xml",
        "views/flights_view.xml",
        "views/service_scope_view.xml",
        "views/vessels_view.xml",
        "views/ocean_shipments_scope_view.xml",
        "views/package_types_view.xml",
        "views/containers_view.xml",
        "views/container_type_view.xml",
        "views/ports_view.xml",
        "views/transport_type_view.xml",
        "views/freight_menus.xml",
    ],
    'demo': [],
    'license': 'AGPL-3',
}
