{
    'name': 'Freight Data',
    'version': '1.0',
    'depends': ['base', 'account'],
    'author': 'GAJA',
    'category': 'services/freight',
    'description': """
    freight data.
    """,
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/res_country_views.xml',
        'views/freight_type_views.xml',
        'views/package_type_views.xml',
        'views/container_type_views.xml',
        'views/bill_of_lading_type_views.xml',
        'views/freight_container_views.xml',
        'views/ocean_shipments_scope_views.xml',
        'views/vessels_views.xml',
        'views/flights_views.xml',
        'views/service_scope_views.xml',
        'views/clearance_type_views.xml',
        'views/commodity_group_views.xml',
        'views/commodity_data_views.xml',
        'views/freight_tags_views.xml',
        'views/document_type_views.xml',
        'views/res_country_group_views.xml',
        'views/incoterms_views.xml',
        'views/ports_cities_views.xml',
        'views/traking_type_views.xml',
        'views/activity_type_views.xml',
        'views/partner_type_views.xml',
        'views/freight_data_menus.xml',
    ],
    'demo': [],
    'application': True,
    'installable': True,
    'license': 'AGPL-3',
}
