{
    "name": "Installment",
    "version": "1.0",
    "summary": "Installment for Odoo",
    "description": "Installment for Odoo",
    "author": "yasp",
    "category": "Sales",
    "website": "https://www.odoo.com",
    "depends": ["base", "sale_subscription", "documents"],
    "data": [
        "security/ir.model.access.csv",
        "wizard/add_emi_wizard_view.xml",
        "views/res_config_settings_views.xml",
        "views/sale_order_view.xml",
        'data/product_data.xml',
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
