{
    'name': "Freight MD",
    'version': '1.0',
    'depends': ['base', 'account'],
    'author': "Vansh",
    'category': 'services/Freight',
    'description': """Find Your data Here""",
    'data': [
        'security/security_freight.xml',
        'security/ir.model.access.csv',
        'views/freight_views.xml',
        'views/port_cities.xml',
        'views/countries.xml',
        'views/county_group.xml',
        'views/freight_type.xml',
        'views/freight_package_type.xml',
        'views/freight_container_type.xml',
        'views/freight_container.xml',
        'views/freight_bill_lading_type.xml',
        'views/freight_ocean_shipment_scope.xml',
        'views/freight_vessel.xml',
        'views/freight_flights.xml',
        'views/service_scope.xml',
        'views/clearance_type.xml',
        'views/tracking_stage.xml',
        'views/activity_type.xml',
        'views/incoterms.xml',
        'views/configuration_commodity_group.xml',
        'views/configuration_commodities.xml',
        'views/configuration_documents_type.xml',
        'views/configuration_freight_tags.xml',
        'views/freight_menus_views.xml',
    ],
    "demo": [
    ],
    'application': True,
    'installable': True,
    'license': "AGPL-3"
}
