from odoo import api, fields, models


class EstateInquiry(models.Model):
    _name = 'estate.inquiry'
    _description = 'This model is the estate inquiry model use to store the inquiry generated by the users'
    
    name = fields.Char(
        string="Name",
        required=True
    )
    email = fields.Char(
        string="Email"
    )
    phone = fields.Char(
        string="Phone No"
    )
    message = fields.Char(
        string="Message"
    )
    property_id = fields.Many2one(
        comodel_name="estate.property",
        string="Property",
        required=True
    )

    @api.model_create_multi
    def create(self, vals):
        inquiry = super(EstateInquiry, self).create(vals)

        template = self.env.ref('real_estate.inquiry_email_template')
        if template:
            template.send_mail(inquiry.id, force_send=True)
        
        return inquiry
